let carousels = [
  {id:1,img:require("../images/carousel/1.jpg")},
  {id:2,img:require("../images/carousel/2.jpeg")},
  {id:3,img:require("../images/carousel/3.jpg")},
  {id:4,img:require("../images/carousel/5.jpeg")},
  // {id:5,img:require("./images/carousel/13.jpg")},
];

let awards=[
  {time:"2019-01-01",award:"2018年——《国剧盛典》青春演技魅力男演员"},
  {time:"2018-12-04",award:"第十五届——MAHB年度先生盛典年度最具潜力演员"},
  {time:"2018-08-02",award:"福布斯中国2018年——30岁以下精英榜"},
  {time:"2018-06-17",award:"2018微博电影之夜——微博人气演员"},
  {time:"2018-01-10",award:" 第14届电视剧南方盛典——年度男主角"},
  {time:"2017-01-11",award:"电视剧南方盛典——年度男配角"},
  {time:"2015-01-2",award:"亚洲影响力东方盛典——最具潜力男演员"},
];

/*图片大小260*220px*/
let collections = [
  {time: "2019年", name: "《盗墓笔记重启》", role: "吴邪", type: "电视剧", desc: "",img:require("../images/roles/wuxie.jpg")},
  {time: "2019年", name: "《我的真朋友》", role: "井然", type: "电视剧", desc: "",img:require("../images/roles/jingran.jpg")},
  {time: "2018年", name: "《知否？知否？应是绿肥红瘦》", role: "齐衡", type: "电视剧", desc: "",img:require("../images/roles/yuanruo.jpg")},
  {time: "2018年", name: "《许你浮生若梦》", role: "罗浮生", type: "电视剧", desc: "",img:require("../images/roles/luofusheng.jpg")},
  {time: "2018年", name: "《镇魂》", role: "沈巍,黑袍使,面面", type: "电视剧", desc: "",img:require("../images/roles/heipaoshi.jpg")},
  {time: "2017年", name: "《花谢花飞花满天》", role: "花无谢", type: "电视剧", desc: "",img:require("../images/roles/huawuxie.jpg")},
  {time: "2017年", name: "《御姐归来》", role: "何开心", type: "电视剧", desc: "",img:require("../images/roles/hekaixin.jpg")},
  {time: "2016年", name: "《边城浪子》", role: "傅红雪", type: "电视剧", desc: "",img:require("../images/roles/fuhongxue.jpg")},
  {time: "2016年", name: "《我的爱对你说》", type: "电视剧", role: "樊伟", desc: "",img:require("../images/roles/fanwei.jpg")},
  {time: "2016年", name: "《新萧十一郎》", type: "电视剧", role: "连城璧", desc: "",img:require("../images/roles/lianchengbi.jpg")},
  {time: "2015年", name: "《芈月传》", type: "电视剧", role: "嬴稷", desc: "",img:require("../images/roles/yingji.jpg")},
  {time: "2014年", name: "《情定三生》", type: "电视剧", role: "迟瑞", desc: "",img:require("../images/roles/chirui.jpg")},
  {time: "2013年", name: "《大明嫔妃》", type: "电视剧", role: "朱常洵", desc: "",img:require("../images/roles/zhuchangxun.jpg")},
  {time: "2013年", name: "《怪医文三块》", type: "电视剧", role: "海东升", desc: "",img:require("../images/roles/haidongsheng.jpg")},
  {time: "2011年", name: "《风雨梵净山》", type: "电视剧", role: "孙如柏", desc: "",img:require("../images/roles/sunrubai.jpg")},
  {time: "2012年", name: "《王阳明》", type: "电视剧", role: "朱厚照", desc: "",img:require("../images/roles/zhuhouzhao.jpg")},
  {time: "2019年", name: "《夏梦狂诗曲》", role: "柯泽", type: "电视剧", desc: "",img:require("../images/roles/keze.jpg")},
  {time: "2014年", name: "《家宴》", role: "冯豆子", type: "电视剧", desc: "",img:require("../images/roles/fengdouzi.jpg")}
];
let links=[
    {desc:"汇总文档版",code:"",link:"http://t.cn/RQx4RyN",author:"https://www.weibo.com/zhuyilongty",name:"朱一龙天涯粉丝团"},
    {desc:"汇总表格版",code:"",link:"http://t.cn/E2ABdCA",author:"https://www.weibo.com/zhuyilongty",name:"朱一龙天涯粉丝团"},
    {desc:"2018.11.16-2018.12.15更新内容 合集下载",code:"915b",link:"http://t.cn/EA2NFz9",author:"https://www.weibo.com/zhuyilongty",name:"朱一龙天涯粉丝团"},
    {desc:"【朱一龙】钢琴弹唱《男孩》LIVE音频版 下载收藏",code:"",link:"https://www.bilibili.com/audio/au680698?type=1",author:"",name:""},
    {desc:"【朱一龙】钢琴弹唱《男孩》LIVE音频版 在线收听",code:"gi20",link:"http://t.cn/EbmdrIj",author:"",name:""},
    {desc:"【朱一龙】2018年度影视作品合辑",code:"",link:"https://www.bilibili.com/video/av39465812",author:"https://www.weibo.com/u/5757034798?from=feed&loc=at&nick=%25E9%25A3%259E%25E4%25BD%25A0%25E8%2584%2591%25E5%25A3%25B3",name:"@飞你脑壳"},
    {desc:"【朱一龙】2018年度影视作品合辑",code:"",link:"http://v.youku.com/v_show/id_XMzk4OTg3ODUwMA==.html?spm=a2hzp.8244740.0.0",author:"https://www.weibo.com/u/5757034798?from=feed&loc=at&nick=%25E9%25A3%259E%25E4%25BD%25A0%25E8%2584%2591%25E5%25A3%25B3",name:"@飞你脑壳"},
    {desc:"【朱一龙】新闻当事人20190106期：《知否》齐衡",code:"",link:"http://t.cn/EGCrCg8",author:"",name:""},
    {desc:" 2018.05.02《我的真朋友》(202181221我的真朋友x时尚芭莎）路透花絮等合集下载",code:"suyt",link:"http://t.cn/R3ooLJE",author:"",name:""},
    {desc:"【第三部分】数字电影作品资源：（替换13部数字电影无水印版）",code:"u3n8 ",link:"http://t.cn/EU8nztq",author:"",name:""},
    {desc:"【第四部分】直播访谈活动等合集: 2018年节目合集（9月）下载：（新增幻乐之城）",code:"7xux",link:"http://t.cn/EA2NFz9",author:"",name:""},
    {desc:" 2018年节目合集（10月）下载：（新增秒懂星课堂）",code:"e52h",link:"http://t.cn/Ezhx6uy",author:"",name:""},
    {desc:" 2018年节目合集（11月）下载：",code:"soxl",link:"http://t.cn/EUmmqAI",author:"",name:""},
    {desc:" 2018年节目合集（12月）下载：",code:"u64o",link:"http://t.cn/EU8nztf",author:"",name:""},
    {desc:"杂志视频资源合集：（新增VogueMe）合集下载收藏：",code:" h4fh",link:"http://t.cn/RX5fEFg",author:"",name:""},
    {desc:"广告推广（全部代言均有更新） 视频:",code:"30oj",link:"http://t.cn/Ezhx6uL",author:"",name:""},
    {desc:"【第六部分】广告推广（全部代言均有更新） 图片:",code:"zpca",link:"http://t.cn/Ezhx63M",author:"",name:""},
    {desc:"【第七部分】其他视频资源合集：（公益歌曲、湖北电视台、CCTV、桔子爱豆）2018（11月）",code:"8bya",link:"http://t.cn/ELGAWUf",author:"",name:""},
    {desc:"【第九部分】语音资源合集：（新增20181215VogueMe公众号语音）语音合集下载收藏",code:"2mu3",link:"http://t.cn/EU8nztx",author:"",name:""},
    {desc:"【第十部分】朱一龙图片资源合集 出席活动图 2018年（7月）：（725优酷超粉日更新）",code:"o7bt",link:"http://t.cn/ReBwOG6",author:"",name:""},
    {desc:"20180818粉丝嘉年华",code:"yyvh",link:"http://t.cn/EZ5nKUN",author:"",name:""},
    {desc:"20180804青春芒果夜",code:"1byu",link:"http://t.cn/EzIsBct",author:"",name:""},
    {desc:"2018年（8月中）：（许你浮生若梦发布会，官方、个站更新）个站",code:"dz9h",link:"http://t.cn/Ez7trqL",author:"",name:""},
    {desc:"20180909上海NIVEA妮维雅新品发布会个站",code:"tnt4",link:"http://t.cn/EZ5nKUp",author:"",name:""},
    {desc:"20180926 路易威登北京Espace Philippe Parreno 典藏精选展览",code:"a3tl",link:"http://t.cn/EzIsBcE",author:"",name:""},
    {desc:"20180928澳大利亚旅游推广暨朱一龙 欢迎仪式",code:"hi6h",link:"http://t.cn/EzIsBcS",author:"",name:""},
    {desc:"20180930幻乐之城新增摄影师蝈蝈小姐图片",code:"ylq4",link:"http://t.cn/EzIsBcN",author:"",name:""},
    {desc:"（10月上）新增联想发布会个站",code:"ea8i",link:"http://t.cn/EU8nzIW",author:"",name:""},
    {desc:"（10月下）新增refa发布会、欧莱雅重庆见面会个站",code:"ayza",link:"http://t.cn/ELGAW4N",author:"",name:""},
    {desc:"2018（11月）",code:"swwe",link:"http://t.cn/EU8nzMK",author:"",name:""},
    {desc:"2018（12月）",code:"4enr",link:"http://t.cn/EU8nzIH",author:"",name:""},
    {desc:"《情定三生》（新增路透）",code:"kksn",link:"http://t.cn/RTNTmz6",author:"",name:""},
    {desc:"《夏梦狂诗曲》（新增20160310开机发布会）",code:"d5ok",link:"http://t.cn/RTNTmzY",author:"",name:""},
    {desc:"《镇魂》  剧照合集（路透更新）",code:"1zwl",link:"http://t.cn/RDsIWFy",author:"",name:""},
    {desc:"《许你浮生若梦》（新增剧照）",code:"8uv8",link:"http://t.cn/RgqgNfi",author:"",name:""},
    {desc:"《知否》（新增路透）",code:"nhhh",link:"http://t.cn/RTNTmZp",author:"",name:""},
    {desc:"《我的真朋友》（新增我的真朋友x时尚芭莎）",code:"fypu",link:"http://t.cn/R3ooLJR",author:"",name:""},
    {desc:"20180816《盗墓笔记重启》（路透更新）",code:"msio",link:"http://t.cn/EvIvKuZ",author:"",name:""},
    {desc:"电影相关图收藏（密战开机发布会个站）",code:"1ilb",link:"http://t.cn/R0zsKra",author:"",name:""},
    {desc:"宣传照相关收藏：（41,46增加）",code:"psho",link:"http://t.cn/R0zsKra",author:"",name:""},
    {desc:"杂志相关图:(2016.10风度，20181120时尚芭莎、20181130SuperELLE公众号、20181130新浪娱乐201812月刊VogueMe)",code:"8jkg",link:"http://t.cn/R0zsHFX",author:"",name:""},
    {desc:"其他图片：（20181123志愿者联盟科技、2018星能量年度公益之星）",code:"4x3l",link:"http://t.cn/RBgg0oA",author:"",name:""},
    // {desc:"",code:"",link:"",author:"",name:""},
  ];
let connections=[
    {name: "朱一龙微薄", link: "https://login.sina.com.cn/sso/login.php?url=https%…heet%2FefnYK7qvQPoib17v%2F&_client_version=0.6.28"},
    {name: "朱一龙博客", link: "http://blog.sina.com.cn/zhuyilongzhuyilong"},
    {name: "朱一龙工作室客", link: "https://www.weibo.com/u/2708359823?is_hot=1"},
    {name: "朱一龙全球粉丝后援会", link: "https://www.weibo.com/u/2552385441?is_hot=1"},
    {name: "朱一龙天涯粉丝团", link: "https://www.weibo.com/zhuyilongty"},
    {name: "微信公众号", link: "zylty0416"},
    {name: "朱一龙天涯粉丝团B站视频集中地", link: "http://space.bilibili.com/20303408/"},
    {name: "朱一龙天涯粉丝团腾讯视频集中地", link: "http://v.qq.com/vplus/8c3e2d4483a676c0374b388a03b2358f#uin=8c3e2d4483a676c0374b388a03b2358f"},
    {name: "朱一龙天涯粉丝团优酷视频集中地", link: "http://i.youku.com/i/UNDAyNDM1MzU1Mg==?spm=a2hzp.8244740.0.0"},
    {name: "朱一龙天涯粉丝团起源地（天涯论坛朱一龙资讯楼）", link: "http://bbs.tianya.cn/post-funinfo-6034874-1.shtml"},
    {name: "朱一龙天涯粉丝团喜马拉雅FM（朱一龙语音在线）", link: "https://www.ximalaya.com/yinyue/16719306/"},
    {name: "朱一龙天涯粉丝团乐乎（资源汇总存档）", link: "http://zhuyilongtianyafensituan.lofter.com/"}
];

export {collections,carousels,awards,links,connections}